### PR TITLE
Use tinyusb midi with esp32S3

### PR DESCRIPTION
**Pull request by davy39**
Hi, 
I'm exploring this nice project and just succeed in getting Midi signal over USB with a ESP32S3 board.
I can even connect to it to GUI via rtmidi.
Could you review this code and merge it ?
Thanks for your work, I'll keep digging into it :)
Cheers

### CODE REVIEW

**Comment by corrados** [comment]
Looks good, thank you :-). Does it only work on PlatformIO or does it also work with ArduinoIDE (which I am currently using)?

When I have time, I'll test your code with my hardware before I merge the code.

@thijstriemstra you might also be interested in this new code. If you have time, it would be good if you could also try it out.

**Comment by thijstriemstra** [comment]
Nice! thanks for the heads up @corrados I'll have to (re-)order a new device for this project first. TBC.

ps. it says 'workflow awaiting approval', could you approve it so the PR can run on github actions (and catch any premature errors)?

**Comment by davy39** [comment]
@corrados I didn't try it with arduino IDE, I find it easier to setup platformio since I've tried it.
@thijstriemstra  Thanks for suggestion. I've approved github actions on my fork.

I'm actually struggling with EEPROM port for ESP32... I think i'll go for Preferences instead since it'll be better supported in the future.

**Comment by corrados** [comment]
There was already support for EEPROM on ESP32 implemented but I disabled it because it was not reliable: https://github.com/corrados/edrumulus/commit/047628fb8afc2596bb764ff08206d113e951a81e
Later on I removed the code completely. On Teensy the EEPROM storage is reliable. But I tested only on an ESP32 and not an ESP32-S3. Maybe the S3 is more stable in this regard.

**Comment by corrados** [comment]
You might also read the change log to see the history of the project, e.g., https://github.com/corrados/edrumulus/blob/main/doc/ChangeLog.md#2022-01-22-r04-store-settings-on-edrumulus

**Comment by davy39** [comment]
Finally, adapting to Preferences was not so difficult to do, and seems to be be more reliable than EEPROM. 
I think that's working... I would be glad if someone with more Edrumulus experience could test it.
Native USB and internal memory together with 20 Analog inputs, ESP32S3 is fantastic :)

Now I need to work on hardware to test the library on my millenium mps 850...

**Comment by 3hhh** [comment]
> Now I need to work on hardware to test the library on my millenium mps 850...

The MPS 850 should be the MPS750x +1 2-zone crash + 2 8" 2-zone meshs -1 10" 2-zone mesh. So you should probably fare well with the MPS750x settings except for maybe the 8" meshs, which the MPS750x doesn't have.

Also, I never got the hihat to work with edrumulus, but admittedly I didn't try too hard.

**Comment by corrados** [comment]
We should not mix up things here. The support for TinyUSB and the support for EEPROM are two different things which should be a separate Pull request.

**Comment by davy39** [comment]
My bad, that's done.

**Comment by thijstriemstra** [comment]
> @thijstriemstra Thanks for suggestion. I've approved github actions on my fork

it was actually directed towards @corrados

**Comment by corrados** [comment]
> My bad, that's done.

Thanks. I just tried out your branch with my ESP32 (no S3) and normal Arduino IDE and I get the following compiler errors:

```
/home/corrados/TMP/edrumulus/edrumulus.ino: In function 'void setup()':
/home/corrados/TMP/edrumulus/edrumulus.ino:51:38: error: 'usbMIDI' was not declared in this scope
   51 | #  define MYMIDI                     usbMIDI
      |                                      ^~~~~~~
/home/corrados/TMP/edrumulus/edrumulus.ino:88:3: note: in expansion of macro 'MYMIDI'
   88 |   MYMIDI.begin();
      |   ^~~~~~
```

**Comment by davy39** [comment]
That's strange, I've just tried out a built for ESP32 Dev Module with Arduino IDE and it works fine.
It looks like for an unknown reason TEENSYDUINO is defined in your case, so usbMIDI is called but not defined for ESP32 platform. Any clue on why ?

**Comment by corrados** [comment]
I was messing around with Arduino IDE/Library updates so I guess it accidentally changed the board type. My fault. I tried it again and now it compiles just fine, thanks.

One more question:
> `platform = espressif32@^6.4.0`

You now use a fixed version if the library. Why does the default version not work for you?
@thijstriemstra What is your opinion to that change?

**Comment by davy39** [comment]
I guess I just copy paste this config on some forums, or play around to make it work, and that was working like that...

Indeed,[ Platform-espressif32](https://github.com/platformio/platform-espressif32) "recommended to pin to a version", but I'm not familiar with coding conventions...

In fact, it works as well with last version (6.5.0) and same with libraries (fortyseveneffects/MIDI Library@^5.0.2
   & adafruit/Adafruit TinyUSB Library@3.1.0), so it actually works with last versions (without reference to any version).

What I understand is that if we pin it to that, we'll be sure some future upgrade will not break the code, and we could change them after testing the future upgrades.

What do you think ?

**Comment by corrados** [comment]
If you pin the version you can be sure that nothing from the outside can break your Gitlab runner. On the other hand, if we always use the newest version, we can quickly see that Edrumulus is no longer compatible to the newest library. I would vote for using the newest version so that we can early see incompatibilities (which is actually the setup we have on main branch).

**Comment by thijstriemstra** [comment]
> You now use a fixed version if the library. Why does the default version not work for you? @thijstriemstra What is your opinion to that change?

I've also had issues with 6.5.0 in a different project, where 6.4.0 was working properly.


> In fact, it works as well with last version (6.5.0) 

In that case, I don't think you have to pin the version nr.

> we'll be sure some future upgrade will not break the code, and we could change them after testing the future upgrades.

True, but we will also not get the bug fixes and enhancements. I would leave it without a version nr and if something breaks we can take a look then.

**Comment by davy39** [comment]
Understood. I've removed version numbers.

**Comment by corrados** [comment]
Thanks, I'll merge now.

**Pull request merged**
