### PR TITLE
GUI: use the MIDI notes provided in the settings

### PR DESCRIPTION
**Pull request by 3hhh**

### CODE REVIEW

**Comment by corrados** [comment]
Interesting concept. I've implemented my own version on a [update_midi_map](https://github.com/corrados/edrumulus/tree/update_midi_map) branch. I only update on settings load since MIDI notes are very rarely changed and in that case it is ok for me to get the updated MIDI notes after a restart of the GUI.

Anyway, it does not work correctly, unfortunately. Since each pad defines all four MIDI notes but usually only uses a subset of these. But the midi map update assumes that all MIDI notes are valid.

**Comment by 3hhh** [comment]
> Anyway, it does not work correctly, unfortunately. Since each pad defines all four MIDI notes but usually only uses a subset of these. But the midi map update assumes that all MIDI notes are valid.

You need to set the unused MIDI notes to 0 or so, yes. Otherwise the reverse mapping isn't unique and it cannot distinguish the notes (the last mapped note is assumed to be the correct one).

**Comment by corrados** [comment]
MIDI note 0 cannot be used because it switches different choke methods, see https://github.com/corrados/edrumulus/discussions/85. Also, auto pad selection does not work anymore with your implementation.

I have fixed both on my branch and it seems to work OK. Can you please test my branch and give some feedback if you are happy with that implementation, too?

**Comment by corrados** [comment]
Argh... That always happens if you change something and do not test it. It always fails :-). I'll fix it.
Thanks for testing.

**Comment by corrados** [comment]
Should be fixed now.

**Comment by corrados** [comment]
FYI: Everything is on main branch now. I deleted my intermediate branch.

**Pull request closed without merging**
