### PR TITLE
remove rtmidi/teensy exception

### PR DESCRIPTION
**Pull request by thijstriemstra**
refs #115

### CODE REVIEW

**Comment by corrados** [comment]
Actually, edrumulus_gui is supported for ESP32 on Windows with the rtmidi option, see: https://github.com/corrados/edrumulus/discussions/16#discussioncomment-5630286

**Comment by thijstriemstra** [comment]
> Actually, edrumulus_gui is supported for ESP32 on Windows with the rtmidi option, see: https://github.com/corrados/edrumulus/discussions/16#discussioncomment-5630286

In that case I've removed the exception and updated PR.

**Comment by corrados** [comment]
Why not simply change the error message to

`No native Edrumulus USB device (e.g., Teensy) or loopMIDI driver found.`

How do you like this error text? This would provide some more help for the user.

**Comment by thijstriemstra** [comment]
sounds good, I'll let you make that change.

**Comment by corrados** [comment]
done :-)

**Pull request closed without merging**
