### PR TITLE
ci: update dependencies and add esp32-s3

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by corrados** [comment]
Thanks for the update. I plan to support the ESP32-S3 and I have already changed the Edrumulus code so that it compiles without an error. Maybe it makes sense to already include a check for ESP32-S3 compilation in your script? What's your opinion?

**Comment by thijstriemstra** [comment]
> ESP32-S3 compilation in your script? What's your opinion?

good idea, I'll add it.

**Comment by corrados** [comment]
Great, thanks :-)

**Comment by corrados** [comment]
Ups, I just saw that it failed with
"
Invalid workflow file: .github/workflows/main.yml#L30
You have an error in your yaml syntax on line 30
"
Can you please take a look at it?

**Pull request merged**
