### PR TITLE
merge forward prototype thijstriemstra

### PR DESCRIPTION
**Pull request by thijstriemstra**
I want to update my prototype to latest version (I was using year old code) so merging it forward. I'm commenting out the customizations I made and starting fresh with new code.

If you see any mistakes in this config, please let me know @corrados

### CODE REVIEW

**Comment by corrados** [comment]
I am using Edrumulus only by using the run_edrumulus script. Therefore, always the edrumulus_gui is used when I use Edrumulus. The advantage of this is that edrumulus_gui takes care of all the settings so that you do not have to modify anything in the preset_settings() function.

If you always use edrumulus_gui as well, the only thing you have to adjust are the analog_pin settings and the number_pads value.

**Comment by thijstriemstra** [comment]
> If you always use edrumulus_gui as well, the only thing you have to adjust are the analog_pin settings and the number_pads value.

Thanks, I'll do that from now on.

**Comment by corrados** [comment]
I assume that you do not want me to merge your custom prototype branch to main, right? At least it does not make sense for me because it is specific to your prototype and should stay on a branch.

**Comment by thijstriemstra** [comment]
> At least it does not make sense for me because it is specific to your prototype and should stay on a branch.

True, sorry for the confusion, I wanted some feedback on my changes but this was probably wrong way to do it hehe. Thanks for the feedback  though!

**Pull request closed without merging**
