### PR TITLE
ci: add platformio build

### PR DESCRIPTION
**Pull request by thijstriemstra**
this uses github actions and platformio to build the code against one or more boards. Testing against Teensy 3.6 for now but other boards can be added easily.

More info on https://docs.platformio.org/en/latest/integration/ci/github-actions.html

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@corrados can you enable github actions for this repository here: https://github.com/corrados/edrumulus/pull/12/checks Otherwise this pull request won't build.

**Comment by corrados** [comment]
> @corrados can you enable github actions for this repository here: https://github.com/corrados/edrumulus/pull/12/checks Otherwise this pull request won't build.

I have now enabled all actions for the Edrumulus project.

**Comment by corrados** [comment]
What do these actions do? Do they build the source code each time I make a Git commit?

**Comment by corrados** [comment]
> on: [push]

It seems so. Is it possible to use a different trigger? To just build it on a specific label? E.g. each time a label is set which starts with "log".

**Comment by thijstriemstra** [comment]
> I have now enabled all actions for the Edrumulus project.

For some reason it's not running the action, perhaps you need to manually hit a button (in this pr interface somewhere) because im a first time contributor.

**Comment by thijstriemstra** [comment]
> To just build it on a specific label? 

What kind of label? A github ticket label? Why?

**Comment by corrados** [comment]
>> I have now enabled all actions for the Edrumulus project.

> For some reason it's not running the action, perhaps you need to manually hit a button (in this pr interface somewhere) because im a first time contributor.

I will merge your pull request and see if that makes a difference.

**Comment by corrados** [comment]
>> To just build it on a specific label?

> What kind of label? A github ticket label? Why?

I was just thinking about saving some resources. But since there are so few code lines we can ignore this. So, it is fine to run the compilation on each commit.

**Comment by thijstriemstra** [comment]
> I will merge your pull request and see if that makes a difference.

Looks like it's working 👍🏼

**Pull request merged**
