### PR TITLE
Teensy 4.1: support ADC pins 14-17

### LINKED ISSUE #102: Teensy: High pins don't work
I just wanted to use pin A17 on a Teensy 4.1 and it didn't work.

I think the reason is that analogRead(17) reads pin 17, which is A3. Teensy forums suggest to use analogRead(A17) instead, but putting A17 as pin for edrumulus didn't work neither. Possibly A17 is defined by some non-Teensy include, I don't know.

According to the Teensy forums this behaviour applies to all pins >= 14. Maybe it even applies to all Arduino boards?

https://forum.pjrc.com/threads/64046-Cannot-find-A14-A17-on-a-Teensy-4-1
https://forum.pjrc.com/threads/54963-trouble-reading-Analog-pins-A14-and-above

### PR DESCRIPTION
**Pull request by 3hhh**
Fixes #102

### CODE REVIEW

**Comment by 3hhh** [comment]
Possibly using absolute/real pin numbers [everywhere](https://github.com/corrados/edrumulus/blob/8111390311f2768b09b4b2dc0f83632740ddf3a2/edrumulus_hardware.cpp#L40-L41) for the Teensy in the form of the `Ax` notation would be even better and get rid of any translation issues.

I can try that as well, if you're interested.

**Comment by corrados** [comment]
If it is just in section "Teensy 4.0/4.1/3.6" and has no influence on my main hardware ESP32 "ESP32 Dual Core" section, then yes. In the end it would just be a translation function from string to int. So, you would define a new vector in get_prototype_pins which contains the strings and then a loop over all values using a Teensy API translation function to generate analog_pins1 integer values. That change would be very small.

**Comment by 3hhh** [comment]
On 10/14/23 09:29, Volker Fischer wrote:
> If it is just in section "Teensy 4.0/4.1/3.6" and has no influence on my main hardware ESP32 "ESP32 Dual Core" section, then yes.

I just added another commit with the other version. Feel free to cherry-pick the one you like.

It worked on my presumably broken Teensy 4.1 (I got some bad readings), but you might want to test on your Teensy 4.0 as well.

**Comment by corrados** [comment]
Thanks, but before I merge anything, I'll wait until you have your new Teensy and are happy with the results :-).

**Comment by 3hhh** [comment]
I tested this with the working Teensy by now. It works just fine.

**Pull request merged**
