### PR TITLE
build: test against upcoming arduino-esp32 3.0

### PR DESCRIPTION
**Pull request by thijstriemstra**
Test against upcoming arduino-esp32 3.0, see https://blog.espressif.com/announcing-the-arduino-esp32-core-version-3-0-0-3bf9f24e20d4

There's also a migration guide for 2.x to 3.x: https://docs.espressif.com/projects/arduino-esp32/en/latest/migration_guides/2.x_to_3.0.html

### CODE REVIEW

**Comment by thijstriemstra** [comment]
Not sure why the build fails with:

```
KeyError: 'framework-arduinoespressif32-libs':
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/platformio/builder/main.py", line 173:
    env.SConscript("$BUILD_SCRIPT")
  File "/home/runner/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/runner/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/runner/.platformio/platforms/espressif32@src-5f117260f75b328038ec9d3fd0e14a68/builder/main.py", line 346:
    target_elf = env.BuildProgram()
  File "/home/runner/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Util/envs.py", line 242:
    return self.method(*nargs, **kwargs)
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/platformio/builder/tools/piobuild.py", line 61:
    env.ProcessProgramDeps()
  File "/home/runner/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Util/envs.py", line 242:
    return self.method(*nargs, **kwargs)
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/platformio/builder/tools/piobuild.py", line 121:
    env.BuildFrameworks(env.get("PIOFRAMEWORK"))
  File "/home/runner/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Util/envs.py", line 242:
    return self.method(*nargs, **kwargs)
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/platformio/builder/tools/piobuild.py", line 342:
    SConscript(env.GetFrameworkScript(name), exports="env")
  File "/home/runner/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 662:
    return method(*args, **kw)
  File "/home/runner/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/runner/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/runner/.platformio/platforms/espressif32@src-5f117260f75b328038ec9d3fd0e14a68/builder/frameworks/arduino.py", line 41:
    SConscript(
  File "/home/runner/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 662:
    return method(*args, **kw)
  File "/home/runner/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/runner/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/runner/.platformio/packages/framework-arduinoespressif32/tools/platformio-build.py", line 40:
    FRAMEWORK_LIBS_DIR = platform.get_package_dir("framework-arduinoespressif32-libs")
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/platformio/platform/_packages.py", line 32:
    pkg = self.get_package(name)
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/platformio/platform/_packages.py", line 29:
    return self.pm.get_package(spec or self.get_package_spec(name))
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/platformio/platform/_packages.py", line 21:
    owner=self.packages[name].get("owner"),
```

**Comment by corrados** [comment]
I'm looking forward to ESP-IDF 5.x since I hope it will support native USB on ESP32-S3. But I fear that we may run into compatibility issues with running Edrumulus on the old ESP32 chip. But let's see...

> There's also a migration guide for 2.x to 3.x

Would be interesting to see if changes are necessary. At least we should avoid using the new API since then we would not be compatible to the old IDF anymore.

> Looks like it's not supported by platformio yet: https://github.com/platformio/platform-espressif32/issues/1225

Ok, I guess in this case you should close this pull request and create a new one as soon as it is supported?

**Comment by thijstriemstra** [comment]
> Ok, I guess in this case you should close this pull request and create a new one as soon as it is supported?

I'll make it a draft PR if that's ok so I can use this to test.

**Comment by sgryphon** [comment]
I have a pull request up for platform-espressif32 that fixes the error: KeyError: 'framework-arduinoespressif32-libs':

https://github.com/platformio/platform-espressif32/pull/1281

You can use the branch in that PR with arduino-esp32#master, but also need to add the location of the library to platform packages overrides as well.

```
platform = https://github.com/sgryphon/platform-espressif32.git#sgryphon/add-esp32-arduino-libs
platform_packages =
    platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#master
    platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/esp32-arduino-libs.git#idf-release/v5.1
```

You can see if your test branch gets past the libs error with the above. 

Note that alpha v3.0.0 has breaking changes, so old code might not work or even compile, the above branch will at least get past the missing libs to the actual compile stage.

**Comment by corrados** [comment]
@thijstriemstra do you have time to check the new code provided by [sgryphon](https://github.com/sgryphon)?

**Comment by corrados** [comment]
@thijstriemstra, I have created a new Pull Request #144 based on your code and the patch from [sgryphon](https://github.com/sgryphon) which replaces your Pull Request here.

@sgryphon, thank you for your patch. It works fine :-)

I'll close this Pull Request now.

**Pull request closed without merging**
